sudo: required
dist: trusty
language: node_js
node_js:
- '6.11'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key
  add -
- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
  main" >> /etc/apt/sources.list.d/google-chrome.list'
- sudo apt-get update -q
- sudo apt-get install -q google-chrome-stable
script:
- ng build
before_deploy:
- npm install -g @angular/cli
- ng build -prod
- zip ./dist/prod
deploy:
  provider: releases
  api_key:
    secure: f1BaMZiBHymh9+uQmXAyYRF8z5A3W/p3jKIeDRiWLwZqzOV9+gCPcB/bMFYcLEKZRBIn3CXPoNH0SrhECrGoNHs2gvlO1KiXD/ZwSntWKPaZw/oi5u2rflVzh2Rf/gOrsew5wXc7jLR4lyIvxJjAvwi8972qaOy3OJPyEFsxwWgISuMXGF5r4iyY5GmsiUJp+bvN/jgar3thMa9LGGZeEqfdSfIFfeDMcbYSB/eKJDMZZlEvdnWS+MN1lmoYsLolFzQdQUgkMuCaGtAbO8bKNPy3ISXjaLNlNXaMDxrhZX3Q0yaYP1LZ1Bi61gMCWpNx+Z3oSqRW/8+c2LJxiu/iFzql1zJfs/1FNhbGMBNy1+YU4o+lQU++IIYUjcuag/VhEj4laB6CmuL/3og5NR7HkVO3yZe6MJobSm3pnPftGDpBFosIdUD6QGqEYNH8VmqpEe7e7nuAOUAw+pY/mwEDOACePvgPsyYMwKLN8zTqfpKNaKS/VSvsRHXQ5ojfBJkPeQCWNYUQK59UUeKs4yDfOB8QPF9HAa+1V5/+dFD2lNKmruuIXzK98e+Ft8T3upL7JaEGAWRlM7rCvMzeRmpm2Vg4b9Do2vGBQX9Gi9l7BKq0qR/q/bELUt4VQhuwldBCoXwvB2EODc4HzCD2iYdzKpLRwR6EycI1YmDIKCdBGO4=
  file: "./dist.zip"
  on:
    repo: vitrivr/vitrivr-ng
