sudo: required
dist: trusty
language: node_js
node_js:
  - '6.11'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g angular-cli
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

script:
  - ls
  - pwd
  - ng test
  - ng build

before_deploy:
  - npm install -g angular-cli
  - npm install
  - ng build -prod
  - zip ./dist/prod

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: ./dist/prod.zip
  skip_cleanup: true
  on:
    tags: true