sudo: required
dist: trusty
language: node_js
node_js:
  - '6.11.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
  - npm install -g angular-cli
  - pwd
  - ls

script:
  - ng test
  - ng build

before_deploy:
  - npm install -g angular-cli
  - ng build -prod
  - zip ./dist/prod

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: ./build/prod.zip
  skip_cleanup: true
    on:
      tags: true